<?php
    $form->setAttribute('action', $this->url('album', ['action' => 'add']));
    $form->setAttribute('method', 'post'); 
    $form->prepare();
    echo $this->form()->openTag($form);
?>
<div class="container mt-3">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Create a new album
                </div>
                <div class="card-body d-flex flex-column justify-content-center align-items-start p-5">
                    <div class="form-group">
                        <?php 
                            echo $this->formRow($form->get('title'));
                        ?>
                    </div>
        
                    <div class="form-group">
                        <?php 
                            echo $this->formRow($form->get('artist'));
                        ?>
                    </div>
        
                    <div class="form-group">
                        <?php 
                            echo $this->formSubmit($form->get('submit'));
                        ?>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<?php
    echo $this->form()->closeTag();
?>