<h1><?= $this->title ?> List</h1>

<a href="<?php echo $this->url('album', [
    'action' => 'add',
]) ?>" class="btn btn-primary btn-sm">
    <div class="d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
        </svg>
        <span class="mx-2">Add</span>
    </div>
</a>

<?php if (count($this->albums) == 0): ?>
    <p>No albums found.</p>
<?php else: ?>
    <table class="table table-striped table-bordered mt-3">
        <tr>
            <th>Album Details</th>
            <th>Actions</th>
        </tr>
        <?php foreach ($this->albums as $index => $album): ?>
            <tr class="my-3">
                <td>
                    ID: <?= ++$index ?> - 
                    Artist: <?= $this->escapeHtml($album->artist) ?> - 
                    Title: <?= $this->escapeHtml($album->title) ?>
                </td>   
                <td>
                    <a href="<?php echo $this->url('album', [
                        'action' => 'edit',
                        'id' => $album->id
                    ]) ?>" class="btn btn-warning btn-sm text-white">
                        <div class="d-flex align-items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                            </svg>
                            <span class="mx-2">Edit</span>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('album', [
                        'action' => 'delete',
                        'id' => $album->id
                    ]) ?>" class="btn btn-danger btn-sm">
                        <div class="d-flex align-items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-archive" viewBox="0 0 16 16">
                                <path d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5zm13-3H1v2h14zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5"/>
                            </svg>
                            <span class="mx-2">Delete</span>
                        </div>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
